services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: aegira-creditappdemo-github-runner

    environment:
      REPO_URL: https://github.com/fadka23/aegira-loan-service-MasKent
      RUNNER_TOKEN: A6HKPKXWVLZDU7HDB25ESSLKKROLC
      RUNNER_NAME: github-runner
      LABELS: docker-local

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-data:/runner/data

    restart: unless-stopped