services:
  postgres:
    image: postgres:15
    container_name: aegira-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aegira
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: aegira-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    image: fadhlya/backend:latest
    container_name: aegira-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aegira
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  frontend:
    image: fadhlya/frontend:latest
    container_name: aegira-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend